### ISSUE TITLE
Permission error creating project from template

### ISSUE THREAD

**Issue by GarthDB** [bit101/tinpig#41]
Running tinpig and selecting a template I can't seem to get past `Project path:`

If I give it a path to an empty directory it responds: `>> 'test' already exists.`

If I give it a path to create a new directory it responds: `>> You don't have access to 'test'.`

I tried running it with sudo without success.

**Comment by bit101** [comment]
the first one is right. It will not create a project in an existing directory. considering adding that as an option at some point.

not sure what's going on with the second one. what path were you giving it?

**Comment by GarthDB** [comment]
I tried a couple:

* `~/Projects/testing`
* `./testing`

**Comment by GarthDB** [comment]
I was running it from `~/Projects`
I'm on MacOS 10.13.3
Node v6.2.2

**Comment by bit101** [comment]
ah... https://www.npmjs.com/package/tinpig#requirements
"Requirements

You'll need npm and an updated version of nodejs. Your version of nodejs should be 8.5.0 or higher, for the file copying functinality that was introduced at that point."

**Comment by GarthDB** [comment]
duh, reading hard. That fixed it.

**Comment by bit101** [comment]
I should specify that in the package.json though. Will do so.

**Comment by bit101** [comment]
good to know that fixed it though. Thanks!

**Comment by bit101** [comment]
I created another issue. https://github.com/bit101/tinpig/issues/42
