### ISSUE TITLE
Ignore .DS_Store

### ISSUE THREAD

**Issue by GarthDB** [bit101/tinpig#43]
I opened my templates directory in finder on my Mac and it created a .DS_Store file.

Afterwards, calling tinpig gives this error:

```
{ Error: ENOTDIR: not a directory, open '/Users/garthdb/.config/tinpig/templates/.DS_Store/tinpig.json'
  errno: -20,
  code: 'ENOTDIR',
  syscall: 'open',
  path: '/Users/garthdb/.config/tinpig/templates/.DS_Store/tinpig.json' }
```

I would say you could ignore non-directory paths in the templates directory but that would cause some problems with #38 

I'm sure there are other system files that could be ignored.

**Comment by bit101** [comment]
oh, yeah... nice.
actually, I can just check for the existence of `tinpig.json` before trying to read it. 

also... stupid .DS_Store files!!!!

**Comment by bit101** [comment]
should be fixed now.
