### ISSUE TITLE
path to templates and config in window "undefined"

### ISSUE THREAD

**Issue by macguffin** [bit101/tinpig#56]
Hi was having a play. The templates and config seemed to be put into an undefined folder. Maybe because I'm on a PC.

My config file is this:
{
  "templatesDir": "undefined/.config/tinpig/templates",
  "userName": "User Name",
  "userEmail": "username@sampledomain.com",
  "invalidPathChars": "â€˜â€œ!#$%&+^<=>` "
} 

Also tinpig configure just seems to bring up the same template selection screen for me.

Thanks

**Comment by macguffin** [comment]
FYI changed - constants.js to this and it seems to be working. Guessing you are on a mac :)

const TINPIG_DIR = `${process.env.USERPROFILE}/.config/tinpig`;

**Comment by bit101** [comment]
Thanks, I'll look into it. I developed and tested it on Linux and Mac, but not so much on Windows.

**Comment by macguffin** [comment]
Cool thanks. I can test on windows if you ever need it.

**Comment by bit101** [comment]
I can too. Just got lazy there. :)

**Comment by bit101** [comment]
Easily able to reproduce on windows.
Looks like the cross platform way to do it is `os.homedir()`
I'll make the fix and do some testing.

**Comment by bit101** [comment]
Easily able to reproduce on windows.
Looks like the cross platform way to do it is `os.homedir()`
I'll make the fix and do some testing.

**Comment by bit101** [comment]
Pushed a fix: version 1.4.3. Seems ok now. Let me know.
